server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com #eureka服务端的实例名称

  client:
    register-with-eureka: false #表示不向注册中心注册自己
    fetchRegistry: false #表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka #设置与Eureka Server交互的地址检查服务和注册服务都需要依赖这个地址。
